### ISSUE TITLE
Small Example app

### ISSUE THREAD

**Issue by sircharleswatson** [devinivy/dogwater#1]
It would be really great if you could make a small example app showing how this works. It looks interesting and I would love to be able to use it but i'm sort of new to node/hapi/js so I can't quite piece it together.

Much appreciated,
Charles

**Comment by devinivy** [comment]
Resolved by #21.  I include a copy-and-paste-able example at the top of the docs.

**Comment by ogrotten** [comment]
To add to this closed issue: the lack of documentation here has chased this user off as I also was trying to figure it out. The c/p example leaves many questions.
