### ISSUE TITLE
Using with postgreSQL

### ISSUE THREAD

**Issue by Sogl** [devinivy/dogwater#31]
Hi!

I'm from this issue:
https://github.com/hapijs/discuss/issues/188

How to specify adapter with `dogwater`? I want to use new ES6 waterline:
https://github.com/waterlinejs/postgresql-adapter
Need some useful examples.

In my situation I already have postgres DB with test data and want to quickly create REST API on Hapi.js. Maybe this tool also can help me?
https://github.com/devinivy/bedwetter
But I don't clearly understand how this can help me =))

**Comment by devinivy** [comment]
Here's a great article that will get you started with the basics: http://blog.webkid.io/how-to-create-a-rest-api-with-hapi/

Once you register dogwater, your waterline collections will be available in convenient places within the hapi framework.  Bedwetter has configurable REST endpoints that integrate with waterline via dogwater.  If you create an API using bedwetter, it will work very similarly in URL patterns and response codes to GitHub's API.
