### ISSUE TITLE
Fixtures Associations

### ISSUE THREAD

**Issue by BransonGitomeh** [devinivy/dogwater#35]
hey, would you be kind enough to provide an example where the fixtures populate an associaltions, 

i know this is not a dog-water issue, but please bare your example on the readme is good and understandable, but after that, there is very little documentation on the internet on how to make associaltions in fixtures, 1:m,m:m,m:1 and any more

this is very usefull for any user who intends to use dogwater for a project, can you refrence any examples  on ho i can do associations in fixtures?

im getting this err

```
Debug: internal, implementation, error 
    Error: Uncaught error: Encountered unexpected error while building join instructions for `.populate("users")`
Details:
[Error: In `.populate("users")`, attempting to populate an attribute that doesn't exist]

```
when trying to follow waterlines docs , please consider this :-)

**Comment by devinivy** [comment]
I'll try to come up with something!  I know @lynnaloo had similar issues.  I think we need a better solution for fixtures than the waterline-fixtures module.  Check out sails-relational-fixtures for a better solution to the problem.

**Comment by BransonGitomeh** [comment]
hey @devinivy thanks for the reply, i have looked at https://github.com/ClickInspire/sails-relational-fixtures already and what turned me off was just the syntax, 

```
"favouriteFruit": {
  "_association": 2,
    "_model": "fruit"
}
```
does not exactly feel right compared to 
```
// sails/config/local.js
fixtures: {
  // note that the order is reversed compared
  // to the One-to-many relation
  order: ['Pet', 'User'],
  User: [
    {
      username: 'Robinson Crusoe',
      models: {
        // to look up the 'name' attribute.
        // Is equivalent to {name: 'Wilson'}.
        pet: ['Wilson']
      }
    }
  ],
  Pet: [
    {
      name: 'Wilson'
    }
  ]
}
```
from https://github.com/arryon/sails-hook-fixtures which feels stick with  more natural

**Comment by BransonGitomeh** [comment]
aah :-) sorry for the slow responce but i realize it was an issue with my code, was asking for a generator module i made for fixtures ,and not calling it as a function hence dogwater was getting `[Function]` instead of the generate fixture data, i have fixed it and i have to say this module is quite good and thanks for the patience :-) :+1:  ill now close this issue
