### ISSUE TITLE
Newbie documentation

### ISSUE THREAD

**Issue by windmaomao** [devinivy/dogwater#36]
for some reason, most of the tutorial and working samples are referring to documentation here,

https://github.com/devinivy/dogwater/tree/v0.4.7

it took me a while to figure that out.

**Comment by devinivy** [comment]
@windmaomao what tutorial are you referring to?  Not sure what I can do about it.  If it's @moklick's tutorial, maybe we can ask him to add a note saying that it uses an old version of dogwater.

**Comment by devinivy** [comment]
Closing this– we can reopen if someone finds there's more to be done about the issue.

**Comment by moklick** [comment]
Hey. Sorry for the delayed response. I am going to update my article in the next days. Thanks for the hint :+1:
