### ISSUE TITLE
Dogwater hides configuration errors returned by Waterline.init

### ISSUE THREAD

**Issue by luckycadow** [devinivy/dogwater#52]
If waterline init returns an error with it's callback no errors are thrown, but Hapi will not handle any requests. I was seeing this with NODE_ENV=production without setting a migration strategy.  Waterline returned an error that safe migrations must be used in production but it was swallowed during plugin registration.

**Comment by luckycadow** [comment]
It looks like there's already a test covering this error being returned, but hapi doesn't do anything with the error given to the onPreStart callback.  I'd be happy to open a PR, just not sure how you want to handle this or if maybe the bug is actually in hapi.

**Comment by devinivy** [comment]
Are you handling errors when you call `server.start(cb)` or `server.initialize(cb)`?  That's where the error would surface rather than during plugin registration.

**Comment by luckycadow** [comment]
That was exactly the problem.  I used a generator and didn't think to look at the startup code.  Compose was handling errors but not server.start.

**Comment by devinivy** [comment]
Great!  Glad you were able to clear it up.
