### ISSUE TITLE
Referencing models from other plugins

### ISSUE THREAD

**Issue by iwasrobbed** [devinivy/dogwater#55]
Apologies for the newbie question, just learning hapi / dogwater / waterline. 

**All crud methods are working fine for me, except when I mixed models in different plugins.**

I have a plugin called `Facebook` and a plugin called `Person` and I'd like to be able to reference `Person` from `Facebook` in order to find or create a person based on whether they exist in some form in the `Facebook` table.

So in `Facebook` I'm using:

```javascript
const Person = request.collections(true).person;
console.log('person identity: ' + Person.identity);
// it prints, so it seems to work?
// person identity: person
```

However, if I try and call `.create` on that `Person` collection, it does nothing / doesn't throw an error and then if I try and print the result it says:

```
const zePerson = yield Person.create({
    firstName: firstName,
    lastName: lastName,
    email: email
});
console.log('zePerson: ' + zePerson);
```

>zePerson: TypeError: request.collections is not a function

What am I missing here? Thanks for the help!

**Comment by iwasrobbed** [comment]
Ah, nevermind. It ended up being a namespace conflict :( That was painful to figure out.

If you have any general advice on mixing models like this (or how to avoid it), I'd appreciate any insights.

**Comment by devinivy** [comment]
Ah, sorry you had troubles with this.  What names were conflicting?  It is not always easy when plugins depend on each other!  I try to minimize that by drawing boundaries between independent parts of an application, perhaps roughly by grouping models together.  But it's not always clear-cut.

**Comment by iwasrobbed** [comment]
I had created some model methods for the various crud calls and some were unfortunately named the same as those used in Waterline (e.g. `create`) so it was not working. I just namespaced them and the issues cleared up

Thanks for the advice!
