### ISSUE TITLE
Accessing postgresql view?

### ISSUE THREAD

**Issue by harsharastogi** [devinivy/dogwater#57]
I understand, one can use request.collections.<table_name> to access underlying sql table. But if one needs to access a table view in a query how do we do that?

**Comment by devinivy** [comment]
Honestly I'm not sure!  I think this is really a question about waterline– maybe try posting in [waterline](https://github.com/balderdashy/waterline) / [sails-mysql](https://github.com/balderdashy/sails-mysql) / [sails-postgresql](https://github.com/balderdashy/sails-postgresql).
