### ISSUE TITLE
Is there a functionality and/or cli for database migrations?

### ISSUE THREAD

**Issue by andorfermichael** [devinivy/dogwater#58]
Hi,

I was wondering if dogwater and/or waterline provide a way for database migrations like, for example, [sequelize-cli](https://github.com/sequelize/cli) does for [Sequelize ORM](https://github.com/sequelize/sequelize).

What I would like to do is to run, for example, `db:migrate --env=development` and all tables and rows and columns are created automatically based on my models.

Thanks in advance.

**Comment by devinivy** [comment]
Waterline itself has some migration strategies that can be set on a per-collection basis (see [here](https://github.com/balderdashy/waterline-docs/blob/c3bcde8e6118b5e9c3712167cec2ca5322adf02c/models/configuration.md#migrate)).  However, they're not well-suited for production.  I would suggest using [knex](http://knexjs.org/)'s migration features, which work quite well.

If you're using a some flavor of SQL with hapi I would highly suggest using [Objection ORM](https://github.com/Vincit/objection.js) with the [schwifty](https://github.com/BigRoomStudios/schwifty) hapi plugin, which is similar to dogwater.  That plugin has much more integrated support with migrations via knex.  And we find Objection to be a pleasure to work with.
