### ISSUE TITLE
Inconvenient usage of Waterline attribute methods

### ISSUE THREAD

**Issue by minecrafter** [devinivy/dogwater#7]
To be specific, Dogwater requires unextended Waterline collections, and `this` is not properly bound. Therefore, models like this will not work (highly simplified to show the point):

    module.exports = {
      attributes: {
        firstName: 'string',
        lastName: 'string',
        getFullName: function() { return this.firstName + ' ' + this.lastName; }
      }
    }

This may be difficult fix without major API changes, however, so this may be of use for future releases only.

**Comment by devinivy** [comment]
I am a little surprised this doesn't work.  I figured waterline would attach model instance methods with the correct context bound.  Can you briefly describe the expected and actual result when using `modelInstance.getFullName`?

**Comment by devinivy** [comment]
@minecrafter, for the sake of demonstration, I wrote a test for this on the model-instance-demo branch within this repo: https://github.com/devinivy/dogwater/compare/master...model-instance-demo .  It works just fine for me!

**Comment by minecrafter** [comment]
Hmm, odd, as it wasn't working for me. I will do some more experiments and get back to you.

**Comment by minecrafter** [comment]
I just got time to get my testing environment going. I'm checking everything now.

**Comment by minecrafter** [comment]
The issue turned out to be related to babel, which is pretty odd. Converting the model to ES5 code works fine, as it turns out. I may need to bring it up with the developers.

**Comment by devinivy** [comment]
Cool– I'll close this out for now.  Feel free to post here whatever you learned, as it could be an issue others have to deal with.  Thanks!
