### ISSUE TITLE
Decorate `request` with `model` rather than set property, make server method sync.

### ISSUE THREAD

**Issue by devinivy** [devinivy/dogwater#8]
This is much cleaner, more hapi-idiomatic than before.

**Comment by kevmannn** [comment]
Hey @devinivy I might be interested in tackling this one. Will look at more of the dogwater source today.

**Comment by devinivy** [comment]
Awesome!  Thanks @kevmannn.

Some resources: 
1. Request decoration (converting `request.model.users` to `request.model('users')`: http://hapijs.com/api#serverdecoratetype-property-method
2. Server methods (see `callback: false` option for sync call): http://hapijs.com/api#servermethodname-method-options

**Comment by devinivy** [comment]
Turns out it's kosher to decorate `request` with an object rather than a method– see https://github.com/hapijs/chairo .  So I'd like to keep the `request.model.users` syntax, but do so with `server.decorate` rather than with an `onRequest` extension as it does currently.

**Comment by devinivy** [comment]
Progress made on branch `decorate`.

**Comment by kevmannn** [comment]
Gotcha! Have forked but haven't gotten very far. My weekend was slightly more discombobulated than I was expecting.

**Comment by devinivy** [comment]
I suggest reforking the `decorate` branch and working from the of the work done there.  Tests still need to be written.

**Comment by devinivy** [comment]
Back up to full coverage on `decorate`, but there's room for tightening and reordering the tests.

**Comment by devinivy** [comment]
This is now the only PR left pending for v1.0.0.  Time to tighten and reorder tests!

**Comment by devinivy** [comment]
Resolved by #22.
